# Generated by Django 4.2.1 on 2023-05-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(db_table='room_amenities', related_name='rooms', to='rooms.amenity'),
        ),
    ]
