version: "3"
services:
  django_database:
    image: postgres:15.2-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file: ./docker-compose.env
    volumes:
      - ./data:/var/lib/postgresql/data
