# Generated by Django 4.1.2 on 2023-03-12 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(blank=True, max_length=250, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'perks',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('country', models.CharField(default='한국', max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('city', models.CharField(default='서울', max_length=80)),
                ('address', models.CharField(max_length=250)),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiences', to='categories.category')),
            ],
            options={
                'db_table': 'experiences',
            },
        ),
    ]
